// Code generated by "stringer -type=DiagnosticSeverity -output=diagnosticseverity_string.go"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityError-1]
	_ = x[SeverityWarning-2]
	_ = x[SeverityInformation-3]
	_ = x[SeverityHint-4]
}

const _DiagnosticSeverity_name = "SeverityErrorSeverityWarningSeverityInformationSeverityHint"

var _DiagnosticSeverity_index = [...]uint8{0, 13, 28, 47, 59}

func (i DiagnosticSeverity) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_DiagnosticSeverity_index)-1 {
		return "DiagnosticSeverity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiagnosticSeverity_name[_DiagnosticSeverity_index[idx]:_DiagnosticSeverity_index[idx+1]]
}
